[package]
name = "minidump-writer"
version = "0.1.0"
authors = ["Martin Sirringhaus"]
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1.3.2"
cfg-if = "1.0"
exception-handler = { path = "../crash-handling/exception-handler" }
goblin = "0.5"
libc = "0.2.74"
memmap2 = "0.5"
memoffset = "0.6"
minidump = "*"
minidump-common = "*"
nix = "0.23"
scroll = "0.11"
tempfile = "3.1.0"
thiserror = "1.0.21"

[dev-dependencies]
uctx = { path = "../crash-handling/uctx" }
debugid = "0.7.3"

[patch.crates-io]
#minidump = { git = "https://github.com/EmbarkStudios/rust-minidump", rev = "228c5d0" }
#minidump-common = { git = "https://github.com/EmbarkStudios/rust-minidump", rev = "228c5d0" }
minidump = { path = "../rust-minidump/minidump" }
minidump-common = { path = "../rust-minidump/minidump-common" }
